### ISSUE TITLE
the data in the ameco package not matching AMECO Online data

### ISSUE THREAD

**Issue by kuantalyst** [expersso/ameco#1]
I installed your package from GitHub, and compared the data to the Online version of AMECO and it doesn't match.

R AMECO package data:
amecodata <- ameco %>% dplyr::filter(sub.chapter == "01 Gross domestic product", title == "Gross domestic product at current prices", year %in% c(2014), unit == "(Mrd PPS)",  cntry %in% c("ITA", "DEU", "FRA", "GBR", "CHE"))

Screenshot attached of same variable in AMECO Online:
<img width="1373" alt="screen shot 2016-01-18 at 21 50 06" src="https://cloud.githubusercontent.com/assets/1278747/12402472/8ea3a424-be2d-11e5-91f8-e697b62f8332.png">

Looks like the database has been updated since this package has been committed: Last update : 05/11/2015

Or am I doing something wrong?

**Comment by expersso** [comment]
Many thanks indeed for this. The package is now updated with the Fall 2015 version, and I've added a unit test that checks whether there is a new update available. The new version should be on CRAN shortly as well.

**Comment by franzprante** [comment]
It seems that the data in the package has not been updated since 9 November 2017 (the date stated in the [readme.md](https://github.com/expersso/ameco). The last AMECO database update took place 3 May 2018 ([see AMECO website](https://ec.europa.eu/info/business-economy-euro/indicators-statistics/economic-databases/macro-economic-database-ameco/ameco-database_en)).

Is there any chance that the package will be updated again?
